services:
  mariadb:
    image: mariadb:latest
    container_name: medihub_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD} # .env 파일에서 로드
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - "3308:3306"
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - springboot-network

  my-app:
    image: ${DOCKER_USERNAME}/medihub:latest
    container_name: medihub
    restart: always
    environment:
      DB_PORT: ${DB_PORT}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
    ports:
      - "8089:8088" # 호스트 포트:컨테이너 내부 포트
    depends_on:
      - mariadb
    networks:
      - springboot-network
    command: ["/wait-for-it.sh", "mariadb:3306", "java", "-jar", "app.jar"]

networks:
  springboot-network:
    driver: bridge

volumes:
  mariadb_data:


