springdoc:
  swagger-ui:
    path: /swagger-ui

# 서버 포트 번호
server:
  port: 8088

spring:
  # .env 파일 읽어오기 위한 설정
  config:
    import:
      - optional:file:.env[.properties]
    # mariadb 연결
  datasource:
    url: jdbc:mariadb://mariadb:3306/${DB_NAME}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect


