apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  namespace: lcrspace # 네임스페이스 지정
  name: lcrrolebind
subjects:
  - kind: Group # 연결할 그룹
    name: lcrgroup
roleRef:
  kind: Role # 연결할 역할
  name: lcrrole
  apiGroup: rbac.authorization.k8s.io