- name: Notify Slack on Success
  if: success()
  id: slack-success
  uses: slackapi/slack-github-action@v2.0.0
  with:
    payload: |
      {
        "channel": "#알림방",  # 실제 채널 ID로 변경
        "attachments": [
          {
            "color": "#36a64f", 
            "title": "${{ github.repository }}",
            "title_link": "https://github.com/${{github.repository}}",
            "text": "GitHub Action 성공",
            "fields": [
              {
                "title": "Repository",
                "value": "${{ github.repository }}",
                "short": true
              },
              {
                "title": "Tag",
                "value": "${{ github.ref_name }}",
                "short": true
              }
            ]      
          }
        ]
      }
  env:
    SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
    SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK

- name: Notify Slack on Failure
  if: failure()
  id: slack-failure
  uses: slackapi/slack-github-action@v2.0.0
  with:
    payload: |
      {
        "channel": "#알림방",  # 실제 채널 ID로 변경
        "attachments": [
          {
            "color": "#ff0000",
            "title": "${{ github.repository }}",
            "title_link": "https://github.com/${{github.repository}}",
            "text": "GitHub Action 실패 :x:",
            "fields": [
              {
                "title": "Repository",
                "value": "${{ github.repository }}",
                "short": true
              },
              {
                "title": "Tag",
                "value": "${{ github.ref_name }}",
                "short": true
              }
            ]      
          }
        ]
      }
  env:
    SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
    SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
